# Generated by Django 4.0.5 on 2022-11-27 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_body',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='isCorrect',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_a',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_b',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_c',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_d',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('D', 'D'), ('B', 'B'), ('C', 'C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=models.TextField(),
        ),
    ]
