# Generated by Django 4.0.5 on 2022-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_answer_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_a',
            new_name='choice_A',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_b',
            new_name='choice_B',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_c',
            new_name='choice_C',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choice_d',
            new_name='choice_D',
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(choices=[('B', 'B'), ('D', 'D'), ('C', 'C'), ('A', 'A')], max_length=1, null=True),
        ),
    ]
