# Generated by Django 4.0.5 on 2022-11-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_answer_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_A',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_B',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_C',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_D',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(choices=[('D', 'D'), ('B', 'B'), ('C', 'C'), ('A', 'A')], max_length=1, null=True),
        ),
    ]
