# Generated by Django 5.0.4 on 2024-05-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_body',
            new_name='questionBody',
        ),
        migrations.RemoveField(
            model_name='takequestion',
            name='question',
        ),
    ]
