# Generated by Django 5.0.6 on 2024-05-10 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_body',
            new_name='choiceBody',
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.ImageField(blank=True, upload_to='api/static/solutions'),
        ),
        migrations.RenameModel(
            old_name='TakeTest',
            new_name='TestAttempt',
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.choice')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionAttempts', to='api.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.question')),
            ],
        ),
        migrations.DeleteModel(
            name='TakeQuestion',
        ),
    ]
