# Generated by Django 5.0.4 on 2024-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tests',
            field=models.ManyToManyField(null=True, to='api.test'),
        ),
    ]
