# Generated by Django 5.0.4 on 2024-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subject_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='tests',
            field=models.ManyToManyField(blank=True, to='api.test'),
        ),
    ]
