# Generated by Django 4.0.5 on 2022-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_choice_a_answer_choice_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(choices=[('C', 'C'), ('D', 'D'), ('A', 'A'), ('B', 'B')], max_length=1, null=True),
        ),
    ]
