# Generated by Django 4.0.4 on 2023-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_answer_choice_a_alter_answer_choice_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(choices=[('D', 'D'), ('A', 'A'), ('C', 'C'), ('B', 'B')], max_length=1, null=True),
        ),
    ]
